### ISSUE TITLE
Produces invalid JSON

### ISSUE THREAD

**Issue by jaypikay** [ryancollingwood/diablo_4_armory_fetcher#1]
https://github.com/ryancollingwood/diablo_4_armory_fetcher/blob/db972215a0c75b5f859426432ecce7965ac99ead/reconstruct_historical_data.py#L16

Using `outfile.write(…)` will produce python strings with single quotes from the dictionary in `data`. Using `json.dump(…)` instead, will ensure the keys are and values - if necessary - are double quoted.

Replacing the old instruction with:
```python
json.dump(data, outfile)
```
is sufficient.

**Comment by ryancollingwood** [comment]
Thank you for reporting this added a fix in commit #c87a46e76b38e42e5488091afcaf73e60f7567ca
I guess I was too hasty to generate an output without checking the output  `>.<`
