### ISSUE TITLE
support duplicate character names

### ISSUE THREAD

**Issue by slippycheeze** [ryancollingwood/diablo_4_armory_fetcher#3]
I'm lazy, and use `SlippyCheeze` as the name of all my characters in D4 right now.

I modified my own copy of the workflow to use `{name}-{uuid}.json` for output, which solves the problem for me.  You should consider adopting something similar here upstream. :)

**Comment by ryancollingwood** [comment]
Thank you for the suggestion, I've made a change to support this: https://github.com/ryancollingwood/diablo_4_armory_fetcher/commit/192525d313c55d5ec5f2523036137c7c94db64e1

May the loot be in your favour SlippyCheeze
